// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhljuvifondghfmvhrrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobGp1dmlmb25kZ2hmbXZocnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTM2NDcsImV4cCI6MjA2NzM4OTY0N30.RKzELjb4D2WaapiB-vZc_NaAAFzN3wPltsaNQUBxqN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});